name = "One Hunter Theme"
version = "0.0.5"
authors = ["Jakub Soboczyński <teziovsky@gmail.com>"]
description = "A port to Zed of the famous One Hunter Theme for VSCode by Railly Hugo"
repository = "https://github.com/teziovsky/zed-one-hunter-theme"
id = "one-hunter-theme"
schema_version = 1
